services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    network_mode: "host"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: mysql://root:example@localhost:3306/mydatabase
    ports:
      - "3000:3000"
    command: sh -c 'sleep 3; npx prisma db push && npm start'
    network_mode: "host"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    network_mode: "host"

volumes:
  mysql-data:
