services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    network_mode: "host"

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"