services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4173:4173"
#    networks:
#      minha-rede:
#        ipv4_address: 192.168.1.10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend 
    ports:
      - "3000:3000"
#    networks:
#      minha-rede:
#        ipv4_address: 192.168.1.11

#networks:
#  minha-rede:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.1.0/24
    